FROM python:3

ENV ENV='production111'

RUN mkdir /code

WORKDIR /code

COPY ./requirements.txt ./
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

COPY . .

EXPOSE 80
