# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:06
from __future__ import unicode_literals

import album.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('e_name', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('estblished_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Establish Date')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=album.models.generate_filename)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Publish Date')),
                ('as_cover', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
            ],
        ),
    ]
