# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='estblished_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Establish Date'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish Date'),
        ),
    ]
