# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='计划内容')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('finish', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(editable=False, max_length=200)),
                ('city_id', models.CharField(editable=False, max_length=200)),
                ('updata_time', models.DateTimeField(auto_now=True)),
                ('aqi', models.IntegerField(editable=False, verbose_name='空气质量指数')),
                ('pm25', models.IntegerField(editable=False)),
                ('tmp', models.IntegerField(editable=False, verbose_name='温度')),
                ('condition', models.IntegerField(editable=False, verbose_name='天气情况')),
                ('pcpn', models.IntegerField(verbose_name='降雨量mm')),
                ('vis', models.IntegerField(verbose_name='能见度km')),
                ('wind_direction', models.IntegerField(editable=False, verbose_name='风向')),
                ('wind_speed', models.IntegerField(editable=False, verbose_name='风速')),
                ('humidity', models.IntegerField(editable=False, verbose_name='湿度')),
            ],
        ),
    ]
